all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ntp_server: time.google.com
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    env: production

  children:
    webservers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
          nginx_worker_processes: 4
        web02:
          ansible_host: 10.0.1.11
          nginx_worker_processes: 4
        web03:
          ansible_host: 10.0.1.12
          nginx_worker_processes: 2
      vars:
        http_port: 80
        https_port: 443
        ssl_cert_path: /etc/ssl/certs
        ssl_key_path: /etc/ssl/private

    appservers:
      hosts:
        app01:
          ansible_host: 10.0.2.10
          app_workers: 8
        app02:
          ansible_host: 10.0.2.11
          app_workers: 8
      vars:
        app_port: 8080
        app_user: appuser
        app_deploy_dir: /opt/app

    dbservers:
      hosts:
        db01:
          ansible_host: 10.0.3.10
          db_role: primary
        db02:
          ansible_host: 10.0.3.11
          db_role: replica
      vars:
        db_port: 5432
        db_data_dir: /var/lib/postgresql/data
        db_backup_dir: /var/backups/postgresql

    monitoring:
      hosts:
        mon01:
          ansible_host: 10.0.4.10
          prometheus_retention: 30d
        mon02:
          ansible_host: 10.0.4.11
      vars:
        node_exporter_port: 9100
        promtail_port: 9080
        loki_url: http://10.0.4.10:3100/loki/api/v1/push
